---
- hosts: regn
  become: yes
  vars:
    nginx_app_domain_name: "www.clouds.kartan.no"
    nginx_app_webroot: /var/www/{{nginx_app_domain_name}}
    letsencrypt_email: kjartanbjorset@gmail.com
    local_project_dir: "{{ playbook_dir.split('/')[0:-1]|join('/') }}"
    
  # roles:
  #   - role: kjartab.nginx-certbot-app
    
  pre_tasks:

    - file: 
        path: /var/www/www.clouds.kartan.no
        state: directory
        owner: travis
        group: web
        mode: 0775
        recurse: yes

