sudo: required
dist: trusty
addons:
  ssh_known_hosts: www.clouds.kartan.no
cache: yarn
language: node_js
script: npm run build
test: true
node_js:
- '7'
before_deploy:
- openssl aes-256-cbc -K $encrypted_47322e492481_key -iv $encrypted_47322e492481_iv
  -in id_rsa_travis.enc -out /tmp//id_rsa_travis -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -rav --no-perms --delete-after --quiet $TRAVIS_BUILD_DIR/dist/ travis@www.clouds.kartan.no:/var/www/www.clouds.kartan.no/
  on:
    branch: master
